export const prompts = [
    "If I die and wake up to ____, I’m leaving.",
    "Don’t open the cursed PDF named ____.",
    "Why did the oracle scream?",
    "The ancient prophecy: ____. ",
    "If you see ____ at midnight, run.",
    "Grandpa's final words were ____.",
    "Satan called. He wants ____ back.",
    "It was all fun and games until ____.",
    "I feel a dark presence whenever I hear ____.",
    "My recurring nightmare features ____.",
    "The SCP Foundation just classified ____.",
    "Summoning a demon using ____.",
    "The most haunted object: ____.",
    "My grandma's old trunk hides ____.",
    "Unexplained 3am sounds were actually ____.",
    "The backrooms level themed after ____."
];

export const answers = [
    "A haunted Furby that won’t shut up.",
    "Silent Zoom calls with no faces.",
    "Cursed chainmail from 2007.",
    "A VHS labeled ‘Don’t Watch’.",
    "Moldy pizza that’s still breathing.",
    "Grandpa’s mystical dentures.",
    "Seeing baby photos in a crime scene.",
    "Communicating with ghosts via WhatsApp.",
    "A Ouija board made of Lego.",
    "Getting Rickrolled IRL.",
    "Balkan curses spoken backwards.",
    "Endless government paperwork.",
    "Dolls that move when you blink.",
    "Hearing ‘Slav squats’ in the attic.",
    "Unsent Angry Birds high scores.",
    "Mom’s search history.",
    "The family group chat after midnight.",
    "My ex’s Spotify playlists.",
    "Radio static saying your name.",
    "The word ‘moist’ carved into a wall.",
    "Kissing a cursed statue for luck.",
    "Losing at Uno for eternity.",
    "Finding out you’re the SCP.",
    "Google Docs crashing… forever."
];