export const prompts = [
    "The most exciting thing in my life: ____.",
    "My hobby nobody cares about.",
    "Every Monday starts with ____.",
    "My group chat is 98% ____.",
    "I pretend to have fun with ____.",
    "What keeps me awake: ____.",
    "When nothing happens, I do ____.",
    "Best part of adulthood: ____.",
    "My most controversial opinion: ____.",
    "Dinner conversation always circles back to ____.",
    "Family reunion activity: ____.",
    "Greatest achievement? ____.",
    "If I had a diary, it’d be full of ____.",
    "My personal highlight of the month: ____.",
    "The only thing breaking my routine: ____.",
    "All my search history is just ____."
];

export const answers = [
    "Scrolling Wikipedia for no reason.",
    "Eating toast, plain.",
    "Replying with ‘ok’ and nothing else.",
    "Updating my calendar, alone.",
    "Staring at the ceiling for motivation.",
    "Googling ‘how to boil water’.",
    "Listening to elevator music.",
    "Reading terms of service.",
    "Comparing laundry detergents.",
    "Microwaving ice cubes just to see.",
    "Socks that never match.",
    "New tab, nothing there.",
    "Organizing folders called ‘Misc’.",
    "Subscribing to newsletters and never reading them.",
    "Renaming group chats to actual dates.",
    "Petting an invisible cat.",
    "Untangling chargers.",
    "Ignoring birthday notifications.",
    "Mediocre cereal for dinner.",
    "Trying to find the remote, giving up.",
    "Writing lists about writing lists.",
    "Cleaning under my bed (just dust).",
    "Waiting for food to get cold.",
    "Rearranging app icons for ‘productivity’.",
    "Favorite color: beige.",
    "Saying ‘same’ to everything.",
    "Counting empty water bottles.",
    "Daydreaming about being slightly less tired.",
    "Watching paint dry (literally).",
    "Resetting passwords I’ll forget."
];