export const answers = [
    "A forbidden OnlyFans link.",
    "Handcuffs, but not the fuzzy kind.",
    "Furry costumes with very questionable accessories.",
    "A tattoo that shouldn't see sunlight.",
    "ASMR for foot lovers.",
    "A Shrek body pillow.",
    "Roleplaying as a traffic cone.",
    "Being the main character in a Wattpad fanfic.",
    "Snapchat streaks gone terribly wrong.",
    "Faking an injury for attention.",
    "BDSM but with Pokémon plushies.",
    "Getting called 'step-bro' in public.",
    "That secret folder named 'uni homework'.",
    "Making eye contact in the bathroom stall.",
    "Catfishing your own ex.",
    "Having a meltdown in IKEA.",
    "Losing a dare AND your dignity.",
    "Sharing nudes in family group by accident.",
    "Kissing your friends “ironically.”",
    "Forgetting the safeword and yelling ‘Skibidi’ instead.",
    "Eating whipped cream off questionable surfaces.",
    "Late night Discord voice calls that go too far.",
    "'It's not illegal if you don't get caught.'",
    "Snapchatting your therapist.",
    "Cosplaying as a minion for money.",
    "Ghosting your situationship via meme.",
    "Running a mafia in Club Penguin."
];

export const prompts = [
    "My Tinder bio would get me banned for ____.",
    "We don't talk about what happened with ____ at 3AM.",
    "The real reason I can't go home for the holidays is ____.",
    "Warning: Do NOT Google ____ at work.",
    "My kinks changed forever after discovering ____.",
    "What’s secretly taped under my bed?",
    "I lost a bet and had to try ____.",
    "The police report mentions ____.",
    "My therapist ghosted me after I confessed ____.",
    "Nobody was ready for Grandma’s story about ____.",
    "There’s a subreddit just for ____.",
    "You can actually get arrested for ____.",
    "The group chat imploded when ____ happened.",
    "The 'special' content on my private folder: ____.",
    "My personal Hell involves endless ____.",
    "The wildest thing at a Balkan wedding: ____."
];